FROM tomcat:9.0.105-jre11-temurin-noble
COPY hello-1.0.war /usr/local/tomcat/webapps/
#ADD /tmp/hw11/hello-1.0.war /usr/local/tomcat/webapps/
#WORKDIR /usr/local/tomcat/webapps/
#ADD hello-1.0.war .
#COPY /tmp/hw11/hello-1.0.war .